# Generated by Django 5.2.3 on 2025-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "e_invoice_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("whatsapp", models.CharField(max_length=20)),
                (
                    "laundry_type",
                    models.CharField(
                        choices=[
                            ("daily_kiloan", "Daily Kiloan"),
                            ("cuci_setrika", "Cuci & Setrika"),
                            ("dry_cleaning", "Dry Cleaning"),
                            ("green_dry_cleaning", "Green Dry Cleaning"),
                            ("laundry_sepatu", "Laundry Sepatu"),
                            ("laundry_tas", "Laundry Tas"),
                            ("laundry_karpet", "Laundry Karpet"),
                            ("laundry_gorden", "Laundry Gorden"),
                            ("laundry_kulit", "Laundry Kulit"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
